export const GET_MENU_DATA = "GET_MENU_DATA";
export const GET_PRODUCTS_DATA = "GET_PRODUCTS_DATA";
export const GET_CATEGORY_DATA = "GET_CATEGORY_DATA";
export const GET_PREVIEW_PRODUCT_DATA = "GET_PREVIEW_PRODUCT_DATA";
export const GET_SLIDER_TOP_DATA = "GET_SLIDER_TOP_DATA";
export const GET_SLIDER_BOTTOM_DATA = "GET_SLIDER_BOTTOM_DATA";
export const GET_FOOTER_DATA = "GET_FOOTER_DATA";
export const GET_NEWS_DATA = "GET_NEWS_DATA";
export const GET_OPEN_NEWS_DATA = "GET_OPEN_NEWS_DATA";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_CONTACTS_DATA = "GET_CONTACTS_DATA";
export const GET_PARTNERS_DATA = "GET_PARTNERS_DATA";
export const SET_CART_DATA = "SET_CART_DATA";
export const RESET_CART = "RESET_CART";

export const SETUP_2FA = "SETUP_2FA";
export const SETUP_2FA_SUCCESS = "SETUP_2FA_SUCCESS";
export const SETUP_2FA_FAILURE = "SETUP_2FA_FAILURE";

export const VERIFY_2FA = "VERIFY_2FA";
export const VERIFY_2FA_SUCCESS = "VERIFY_2FA_SUCCESS";
export const VERIFY_2FA_FAILURE = "VERIFY_2FA_FAILURE";

export const DISABLE_2FA = "DISABLE_2FA";
export const DISABLE_2FA_SUCCESS = "DISABLE_2FA_SUCCESS";
export const DISABLE_2FA_FAILURE = "DISABLE_2FA_FAILURE";

export const LOGIN_2FA_REQUIRED = "LOGIN_2FA_REQUIRED";
export const TWO_FACTOR_VERIFIED = "TWO_FACTOR_VERIFIED";
export const CLEAR_2FA_STATE = "CLEAR_2FA_STATE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REGISTER = 'USER_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_STEP_SUCCESS = 'REGISTER_STEP_SUCCESS';
export const RESET_REGISTRATION_STEP = 'RESET_REGISTRATION_STEP';
