export const USER_LOGIN = 'USER_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_2FA_REQUIRED = 'LOGIN_2FA_REQUIRED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const TOGGLE_2FA_REQUEST = 'TOGGLE_2FA_REQUEST';
export const TOGGLE_2FA_SUCCESS = 'TOGGLE_2FA_SUCCESS';
export const TOGGLE_2FA_FAILURE = 'TOGGLE_2FA_FAILURE'; 